export const menu = [
  {
    itemName: "Burger",
    inStock: "False",
    price: "$6.99",
    vegetarian: "False",
    wagyu: "False",
    image: "",
  },
  {
    itemName: "Dominic",
    inStock: "True",
    price: "$1.99",
    vegetarian: "False",
    wagyu: "True",
    image: "",
  },
  {
    itemName: "Filet Mignon",
    inStock: "True",
    price: "$200",
    vegetarian: "False",
    wagyu: "True",
    image: "",
  },
  {
    itemName: "",
    inStock: "",
    price: "$",
    vegetarian: "",
    wagyu: "",
    image: "",
  },
  {
    itemName: "",
    inStock: "",
    price: "$",
    vegetarian: "",
    wagyu: "",
    image: "",
  },
  {
    itemName: "",
    inStock: "",
    price: "$",
    vegetarian: "",
    wagyu: "",
    image: "",
  },
  {
    itemName: "",
    inStock: "",
    price: "$",
    vegetarian: "",
    wagyu: "",
    image: "",
  },
  {
    itemName: "",
    inStock: "",
    price: "$",
    vegetarian: "",
    wagyu: "",
    image: "",
  },
];
